name: Most used (with details)

on:
  # Roda a cada 24 horas (diariamente) para atualizar o gráfico
  schedule:
    - cron: '0 0 * * *'
  # Permite rodar o workflow manualmente pela aba "Actions"
  workflow_dispatch:

jobs:
  github-metrics:
    # O runner (ambiente) que irá executar a ação
    runs-on: ubuntu-latest
    
    # === CORREÇÃO ADICIONADA AQUI ===
    permissions:
      contents: write # ESSENCIAL: Permite que a Ação salve o arquivo SVG no repositório
      
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.details.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
              html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
              gnuplot
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 5
          output_branch: main
          output_directory: svg
